version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Fix checkout permissions
          command: sudo chmod 777 -R ~
      - run :
          name: Run PHPCS Tests
          command: |
            cd .tests
            echo $PWD
            ls -lart
            composer install --prefer-source --no-interaction
            ./bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/
            composer test
workflows:
  version: 2
  build-n-notify:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
